# POST http://localhost:8080/login HTTP/1.1
# content-type: application/json

# {
#     "cid": "333",
#     "password": "333"
# }

GET http://localhost:8080/markComplete/10730
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiIzMjEiLCJyb2xlIjoiVklFVyIsImlhdCI6MTYxMTU5MzgzNywiZXhwIjoxNjExNjgwMjM3fQ.JjsmlidxyJ_cxeJ-mydqPt7cqvn9F7uzonP-RBSs5kk
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiIzMzMiLCJyb2xlIjoiRURJVCIsImlhdCI6MTYxMTU5Mzk2MiwiZXhwIjoxNjExNjgwMzYyfQ.B6_dBxtd2dY0MwvElj4UpSPEwLj7PNBWU6iFEBf03YE